"""Add prompt_version field to Analytics

Revision ID: 665bc0f79623
Revises: cf554c4884d9
Create Date: 2024-12-02 22:49:35.864349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665bc0f79623'
down_revision = 'cf554c4884d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_version', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_column('prompt_version')

    # ### end Alembic commands ###
