"""Add username field to Analytics

Revision ID: aea3f6cd8a43
Revises: 665bc0f79623
Create Date: 2024-12-02 22:50:31.241192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea3f6cd8a43'
down_revision = '665bc0f79623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
